const $=id=>document.getElementById(id);
const STOCK_KEY='monti.web.stock.v3';
const DB_NAME='monti-compras-web';
const DB_VERSION=1;
let parsedData=null;
let currentFileMeta=null;
let currentOrderFilter='all';

const stockItems=[
 ['Ñoquis','kg','La Artesanal'],['Fusiles','kg','La Artesanal'],['Macarrones','kg','La Artesanal'],['Spaghetti','kg','La Artesanal'],['Ravioles pollo y verdura','cajas','La Artesanal'],['Ravioles de ricota','cajas','La Artesanal'],['Raviolones de batata','cajas','La Artesanal'],['Pan de volcán','unidades','La Artesanal'],
 ['BOLSA TUCO X 4 kl','bolsas','Centro de Producción'],['BOLSA Bolo x4 kg','bolsas','Centro de Producción'],['Bolsa Pesto x 1kg','bolsas','Centro de Producción'],['Bolsa blanca x 2 kilos','bolsas','Centro de Producción'],['Bolsa de cheddar x 4kg','bolsas','Centro de Producción'],['Bolsa Mix de Queso x 2kl','bolsas','Centro de Producción'],['FOCACCIA X UNID','unidades','Centro de Producción'],['LASAGNA BOLOGNESA','unidades','Centro de Producción'],['LASAGANA VERDE','unidades','Centro de Producción'],['Milanesa vacuna x 3kg','paquetes','Centro de Producción'],['Empanadas x 6','packs','Centro de Producción'],['Meat Ball x 5 porciones','packs','Centro de Producción'],['GRAND BRASATO X 2','cajas','Centro de Producción'],
 ['Milanesa pollo x 5kg','cajas','Breaders'],
 ['BOLSON DE PLATOS X300U','packs','Packaging'],['BOLSAS PASTA X500','packs','Packaging'],['PLATOS MACANDCHESS X200','packs','Packaging'],['MANTELES MONTI X1000','packs','Packaging'],['PARAFINADO MONTI X2000','packs','Packaging'],['Cinta MONTI x unid','unidades','Packaging'],['CAJAS MILANESA X100','packs','Packaging'],['CAJAS DE SANDWICH X 100','packs','Packaging'],['Cinta FOCACCI x 10 unids','packs','Packaging'],['CAJA VOLCAN X100','packs','Packaging'],['POTES SALSA X100','packs','Packaging'],['BANDEJAS POSTRES X100U','packs','Packaging'],['BOLSAS GRANDES X1200','packs','Packaging'],['juego de cucharon x 12','packs','Packaging']
];

const norm=v=>MontiEngine.norm(v);
const rows=sheet=>XLSX.utils.sheet_to_json(sheet,{defval:''});
function col(row,...names){for(const name of names){const found=Object.keys(row).find(k=>norm(k)===norm(name));if(found!==undefined)return row[found]}return ''}
function asDate(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?new Date(d.y,d.m-1,d.d,12):null}const s=String(v||'').trim();if(!s)return null;const m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})/);if(m){let y=+m[3];if(y<100)y+=2000;return new Date(y,+m[2]-1,+m[1],12)}const d=new Date(s);return isNaN(d)?null:d}
const fmtDate=d=>d?new Date(d).toLocaleDateString('es-AR'):'—';
const isCancelled=v=>['si','sí','true','1','yes'].includes(norm(v));
const getStock=()=>JSON.parse(localStorage.getItem(STOCK_KEY)||'{}');

function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('cache'))db.createObjectStore('cache')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbSet(key,value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('cache','readwrite');tx.objectStore('cache').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function dbGet(key){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction('cache','readonly').objectStore('cache').get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbDelete(key){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('cache','readwrite');tx.objectStore('cache').delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}

function serializeParsed(data){return {sales:data.sales.map(x=>({...x,date:x.date?.toISOString()||null})),modifiers:data.modifiers.map(x=>({...x,date:x.date?.toISOString()||null}))}}
function reviveParsed(data){if(!data)return null;return {sales:(data.sales||[]).map(x=>({...x,date:x.date?new Date(x.date):null})),modifiers:(data.modifiers||[]).map(x=>({...x,date:x.date?new Date(x.date):null}))}}

function navigate(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.dataset.viewPanel===view));document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view));const btn=document.querySelector(`.nav-item[data-view="${view}"]`);$('pageTitle').textContent=btn?.textContent||'Monti Compras';$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.view)));
$('menuToggle').addEventListener('click',()=>$('sidebar').classList.toggle('open'));
$('viewOrdersBtn').addEventListener('click',()=>navigate('orders'));
$('quickUpload').addEventListener('click',()=>{navigate('fudo');$('fileInput').click()});

function renderStock(){const saved=getStock(),q=norm($('stockSearch')?.value||''),provider=$('stockProvider')?.value||'all';const filtered=stockItems.filter(([name,,p])=>(!q||norm(name).includes(q))&&(provider==='all'||p===provider));$('stockGrid').innerHTML=`<div class="stock-head"><span>Insumo</span><span>Proveedor</span><span>Unidad de carga</span><span>Stock</span></div>`+filtered.map(([name,unit,p])=>{const idx=stockItems.findIndex(x=>x[0]===name);return `<div class="stock-row"><strong>${name}</strong><span class="provider-cell">${p}</span><span class="unit-cell">${unit}</span><input data-stock="${idx}" type="number" step="0.01" inputmode="decimal" value="${saved[name]??''}" placeholder="0"></div>`}).join('')}
$('stockSearch').addEventListener('input',renderStock);$('stockProvider').addEventListener('change',renderStock);
$('saveStock').addEventListener('click',()=>{const obj=getStock();document.querySelectorAll('[data-stock]').forEach(input=>{const idx=Number(input.dataset.stock);obj[stockItems[idx][0]]=Number(input.value||0)});localStorage.setItem(STOCK_KEY,JSON.stringify(obj));$('saveStock').textContent='Guardado ✓';setTimeout(()=>$('saveStock').textContent='Guardar stock',1200);generateOrders();renderDashboard()});

$('fileInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});await processWorkbook(wb,file.name,{buffer:buf,size:file.size,type:file.type,lastModified:file.lastModified})}catch(err){console.error(err);alert('No pude leer el archivo. Verificá que sea un Excel de Fudo válido.')}});

async function processWorkbook(wb,fileName,filePayload=null){
 const sheetInfo=[],sales=[],modifiers=[],dates=[];let cancelledMods=0,totalSales=0;
 wb.SheetNames.forEach(name=>{const r=rows(wb.Sheets[name]),sn=norm(name);sheetInfo.push([name,r.length]);
  if(['ventas','adiciones'].includes(sn))r.forEach(x=>{const cancelled=isCancelled(col(x,'Cancelada','Cancelado')),qty=Number(col(x,'Cantidad')||1),date=asDate(col(x,'Creación','Creacion','Fecha')),product=String(col(x,'Producto')||'').trim();if(date)dates.push(date);if(!cancelled)totalSales+=qty;sales.push({orderId:String(col(x,'Id. Venta','Id Venta','Id. venta')||''),product,category:String(col(x,'Categoría','Categoria')||''),qty,date,cancelled,source:name,modifier:false})});
  if(sn==='adiciones de modificadores')r.forEach(x=>{const cancelled=isCancelled(col(x,'Cancelada','Cancelado'));if(cancelled)cancelledMods++;const date=asDate(col(x,'Creación','Creacion','Fecha'));if(date)dates.push(date);const m={orderId:String(col(x,'Id. Venta','Id Venta')||''),product:String(col(x,'Producto')||''),group:String(col(x,'Grupo modificador','Grupo')||''),modifier:String(col(x,'Modificador')||''),qty:Number(col(x,'Cantidad')||1),date,cancelled,source:name};modifiers.push(m);sales.push({...m,product:m.modifier,category:m.group,modifier:true})})
 });
 parsedData={sales,modifiers};dates.sort((a,b)=>a-b);const chicken=modifiers.filter(m=>!m.cancelled&&norm(m.group)==='tipo de milanesa'&&norm(m.modifier).includes('pollo')).reduce((a,m)=>a+m.qty,0),beef=modifiers.filter(m=>!m.cancelled&&norm(m.group)==='tipo de milanesa'&&norm(m.modifier).includes('carne')).reduce((a,m)=>a+m.qty,0);
 currentFileMeta={fileName,at:new Date().toISOString(),sheets:sheetInfo,dateFrom:dates[0]?.toISOString()||null,dateTo:dates.at(-1)?.toISOString()||null,totalSales,mods:modifiers.length,chicken,beef,cancelledMods};
 if(filePayload){await dbSet('originalExcel',{name:fileName,buffer:filePayload.buffer,size:filePayload.size,type:filePayload.type,lastModified:filePayload.lastModified,savedAt:currentFileMeta.at});await dbSet('parsedData',serializeParsed(parsedData));await dbSet('fileMeta',currentFileMeta)}
 updateFudoUi();generateOrders();renderDashboard();
}

function updateFudoUi(){if(!currentFileMeta){$('statusChip').textContent='Sin datos';$('sideStatusText').textContent='Sin Excel cargado';$('sideStatusDot').classList.remove('ok');$('fudoFileName').textContent='Todavía no se cargó un Excel';$('fileMeta').textContent='Elegí el Excel completo exportado desde Fudo.';$('storageStatus').textContent='Sin archivo guardado.';return}const m=currentFileMeta;$('salesCount').textContent=Math.round(m.totalSales||0).toLocaleString('es-AR');$('modsCount').textContent=(m.mods||0).toLocaleString('es-AR');$('dateFrom').textContent=fmtDate(m.dateFrom);$('dateTo').textContent=fmtDate(m.dateTo);$('chickenCount').textContent=(m.chicken||0).toLocaleString('es-AR');$('beefCount').textContent=(m.beef||0).toLocaleString('es-AR');$('fudoFileName').textContent=m.fileName;$('fileMeta').textContent=`Actualizado ${new Date(m.at).toLocaleString('es-AR')} · ${m.sheets?.length||0} hojas detectadas`;$('statusChip').textContent='Excel guardado';$('sideStatusText').textContent='Excel disponible';$('sideStatusDot').classList.add('ok');$('storageStatus').innerHTML=`<strong>${m.fileName}</strong><br>Guardado localmente el ${new Date(m.at).toLocaleString('es-AR')}. Se recupera aunque cierres el navegador.`;$('sheetAudit').innerHTML=(m.sheets||[]).map(([n,c])=>`<div class="audit-row"><span>${n}</span><strong>${Number(c).toLocaleString('es-AR')} filas</strong></div>`).join('')+`<div class="audit-row"><span>Modificadores cancelados excluidos</span><strong>${m.cancelledMods||0}</strong></div>`}

$('clearExcel').addEventListener('click',async()=>{if(!confirm('¿Quitar el Excel guardado de este dispositivo?'))return;await dbDelete('originalExcel');await dbDelete('parsedData');await dbDelete('fileMeta');parsedData=null;currentFileMeta=null;updateFudoUi();generateOrders();renderDashboard()});

function orderRows(order){if(!order.lines?.length)return '<div class="empty">Sin pedido sugerido con el stock actual.</div>';return `<div class="order-table">${order.lines.map(l=>`<div class="order-row"><span><b>${l.name}</b><small>${l.note||''}</small></span><strong>${Number(l.qty).toLocaleString('es-AR',{maximumFractionDigits:2})} ${l.unit||''}</strong></div>`).join('')}</div>`}
function standardOrderCard(order,key){const cov=order.plan?.coverage||[];return `<article class="card order-card" data-order-kind="${key}"><div class="order-head"><div><p class="eyebrow">${order.provider}</p><h3>${order.provider}</h3><div class="order-meta">Entrega ${fmtDate(order.plan?.delivery)} · cubre ${cov.map(fmtDate).join(', ')}</div></div><span class="badge ${order.lines?.length?'warn':'ok'}">${order.lines?.length||0} ítems</span></div>${orderRows(order)}${order.warning?`<p class="muted">${order.warning}</p>`:''}</article>`}
function artesanalCard(normal,special){const normalCov=normal.plan?.coverage||[],specialHas=special?.lines?.length>0;return `<article class="card order-card" data-order-kind="artesanal"><div class="order-head"><div><p class="eyebrow">LA ARTESANAL</p><h3>La Artesanal</h3><div class="order-meta">Entrega ${fmtDate(normal.plan?.delivery)} · cubre ${normalCov.map(fmtDate).join(', ')}</div></div><span class="badge ${normal.lines?.length||specialHas?'warn':'ok'}">${(normal.lines?.length||0)+(special?.lines?.length||0)} ítems</span></div>${orderRows(normal)}<div class="special-note"><strong>🗓 Día 29 integrado automáticamente</strong><div class="muted">${specialHas?`Refuerzo detectado para el ${fmtDate(special.plan?.delivery)}. El cálculo usa el histórico de días 29 y lo muestra dentro de La Artesanal.`:`No hace falta un refuerzo adicional con los datos y stock actuales para el ${fmtDate(special?.plan?.delivery)}.`}</div>${specialHas?orderRows(special):''}</div></article>`}

function generateOrders(){if(!parsedData){$('ordersGrid').innerHTML='<div class="empty card">Importá un Excel para calcular pedidos.</div>';renderNextOrders([]);return}const stock=getStock(),now=new Date(),art=MontiEngine.artOrder(stock,now),d29=MontiEngine.day29Order(stock,art,parsedData.sales,now),cdp=MontiEngine.cdpOrder(parsedData,stock,now,false),cdp29=MontiEngine.cdpOrder(parsedData,stock,now,true),breaders=MontiEngine.breadersOrder(parsedData,stock,now),packaging=MontiEngine.packagingOrder(parsedData,stock,now);const cards=[{key:'artesanal',html:artesanalCard(art,d29),order:art,special:d29},{key:'cdp',html:standardOrderCard(cdp,'cdp')+(cdp29.lines?.length?`<article class="card order-card" data-order-kind="cdp"><div class="special-note"><strong>🗓 Refuerzo CDP día 29</strong><div class="muted">Integrado al proveedor CDP para ${fmtDate(cdp29.plan?.delivery)}.</div>${orderRows(cdp29)}</div></article>`:''),order:cdp},{key:'breaders',html:standardOrderCard(breaders,'breaders'),order:breaders},{key:'packaging',html:standardOrderCard(packaging,'packaging'),order:packaging}];$('ordersGrid').innerHTML=cards.filter(c=>currentOrderFilter==='all'||c.key===currentOrderFilter).map(c=>c.html).join('');const p=MontiEngine.plans(now);$('planMeta').textContent=`La Artesanal ${fmtDate(p.art.delivery)} · CDP ${fmtDate(p.cdp.delivery)} · Breaders ${fmtDate(p.breaders.delivery)} · margen 20%.`;renderNextOrders(cards);renderAlerts({art,d29,cdp,cdp29,breaders,packaging})}

function renderNextOrders(cards){if(!parsedData){$('nextOrdersTable').innerHTML='<div class="empty">Cargá un Excel para ver próximos pedidos.</div>';return}const map=cards.map(c=>({name:c.key==='artesanal'?'La Artesanal':c.key==='cdp'?'Centro de Producción':c.key==='breaders'?'Breaders':'Packaging',order:c.order}));$('nextOrdersTable').innerHTML=`<table><thead><tr><th>Proveedor</th><th>Entrega</th><th>Cobertura</th><th>Estado</th></tr></thead><tbody>${map.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${fmtDate(x.order.plan?.delivery)}</td><td>${x.order.plan?.coverage?.length||'—'} días</td><td><span class="badge ${x.order.lines?.length?'warn':'ok'}">${x.order.lines?.length?`${x.order.lines.length} ítems`:'Sin pedido'}</span></td></tr>`).join('')}</tbody></table>`}
function renderAlerts(o){const alerts=[];if(o.d29?.lines?.length)alerts.push({text:`Día 29: La Artesanal requiere refuerzo especial para ${fmtDate(o.d29.plan?.delivery)}.`,kind:'warn'});if(o.cdp29?.lines?.length)alerts.push({text:`Día 29: CDP también tiene refuerzo calculado para ${fmtDate(o.cdp29.plan?.delivery)}.`,kind:'warn'});if(!Object.keys(getStock()).length)alerts.push({text:'Todavía no hay stock guardado; los pedidos pueden quedar sobredimensionados.',kind:'danger'});const total=[o.art,o.cdp,o.breaders,o.packaging].reduce((a,x)=>a+(x.lines?.length||0),0);if(total===0)alerts.push({text:'No hay compras sugeridas con el stock actual.',kind:'ok'});$('alertsList').innerHTML=alerts.map(a=>`<div class="alert-item"><span>${a.text}</span><span class="badge ${a.kind}">${a.kind==='ok'?'OK':'Revisar'}</span></div>`).join('')||'<div class="empty">Sin alertas.</div>';$('alertCount').textContent=alerts.filter(a=>a.kind!=='ok').length;$('alertCaption').textContent=alerts.length?'Revisión automática':'Sin alertas'}
function renderDashboard(){if(!currentFileMeta){$('dashExcelStatus').textContent='Sin cargar';$('dashExcelMeta').textContent='—';$('dashPeriod').textContent='—';return}$('dashExcelStatus').textContent='Guardado';$('dashExcelMeta').textContent=new Date(currentFileMeta.at).toLocaleString('es-AR');$('dashPeriod').textContent=`${fmtDate(currentFileMeta.dateFrom)} → ${fmtDate(currentFileMeta.dateTo)}`}

$('generateOrders').addEventListener('click',generateOrders);
document.querySelectorAll('[data-order-filter]').forEach(btn=>btn.addEventListener('click',()=>{currentOrderFilter=btn.dataset.orderFilter;document.querySelectorAll('[data-order-filter]').forEach(x=>x.classList.toggle('active',x===btn));generateOrders()}));

async function restoreCachedExcel(){try{currentFileMeta=await dbGet('fileMeta')||null;parsedData=reviveParsed(await dbGet('parsedData'));updateFudoUi();renderDashboard();generateOrders()}catch(err){console.warn('No se pudo restaurar cache local',err)}}

renderStock();updateFudoUi();renderDashboard();restoreCachedExcel();